package com.app.empire.gameaccount.exception;
public class Errors {
    public static final int UNKNOW                   = 1;
    public static final int UNKNOW_ACCOUNT           = 2;
    public static final int UNKOWN_SOURCE            = 3;
    public static final int ILLEGAL_SESSIONID        = 4;
    public static final int NOT_ENOUGH_BALANCE       = 5;
    public static final int ILLEGAL_VALUE            = 6;
    public static final int ERROR_OLD_PASSWORD       = 7;
    public static final int ILLEGAL_PHONE            = 8;
    public static final int NOT_ENOUGH_TOKEN         = 9;
    public static final int REGISTER_FIELD           = 10;
    public static final int DUPLICATE_NAME           = 101;
    public static final int NULL_NAME                = 102;
    public static final int ILLEGAL_NAME_CHAR        = 103;
    public static final int ILLEGAL_LENGTH           = 104;
    public static final int NULL_PASSWORD            = 105;
    public static final int ILLEGAL_PASSWORD_CHAR    = 106;
    public static final int ILLEGAL_PASSWORD_LENGTH  = 107;
    public static final int ILLEGAL_GAMECODE         = 108;
    public static final int NULL_GAMECODE            = 109;
    public static final int REGISTER_COUNT_NOTENOUGH = 110;
    public static final int REGISTER_INFO_NOTFULL    = 111;
    public static final int ERROR_NAMEORPASSWORD     = 201;
    public static final int ALREADY_LOGON            = 202;
    public static final int NO_LOGON                 = 203;
    public static final int ERROR_GAME               = 204;
    public static final int ACCOUNT_FREEZE           = 205;
    public static final int ACCOUNT_INVALID          = 206;
    public static final int TIME_LIMIT               = 207;
    public static final int LOGIN_FIELD              = 208;
}
