// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: army/PlayerPositionInfoMsg.proto

package com.app.empire.protocol.pb.army;

public final class PlayerPositionInfoProto {
  private PlayerPositionInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerPositionInfoMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerPositionInfoMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .PostionMsg curPos = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    boolean hasCurPos();
    /**
     * <code>optional .PostionMsg curPos = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg getCurPos();
    /**
     * <code>optional .PostionMsg curPos = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder getCurPosOrBuilder();

    /**
     * <code>optional .PostionMsg prePos = 2;</code>
     *
     * <pre>
     *上一次记录位置
     * </pre>
     */
    boolean hasPrePos();
    /**
     * <code>optional .PostionMsg prePos = 2;</code>
     *
     * <pre>
     *上一次记录位置
     * </pre>
     */
    com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg getPrePos();
    /**
     * <code>optional .PostionMsg prePos = 2;</code>
     *
     * <pre>
     *上一次记录位置
     * </pre>
     */
    com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder getPrePosOrBuilder();
  }
  /**
   * Protobuf type {@code PlayerPositionInfoMsg}
   */
  public static final class PlayerPositionInfoMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PlayerPositionInfoMsg)
      PlayerPositionInfoMsgOrBuilder {
    // Use PlayerPositionInfoMsg.newBuilder() to construct.
    private PlayerPositionInfoMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerPositionInfoMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerPositionInfoMsg defaultInstance;
    public static PlayerPositionInfoMsg getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerPositionInfoMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerPositionInfoMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = curPos_.toBuilder();
              }
              curPos_ = input.readMessage(com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(curPos_);
                curPos_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = prePos_.toBuilder();
              }
              prePos_ = input.readMessage(com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(prePos_);
                prePos_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.empire.protocol.pb.army.PlayerPositionInfoProto.internal_static_PlayerPositionInfoMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.empire.protocol.pb.army.PlayerPositionInfoProto.internal_static_PlayerPositionInfoMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg.class, com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerPositionInfoMsg> PARSER =
        new com.google.protobuf.AbstractParser<PlayerPositionInfoMsg>() {
      public PlayerPositionInfoMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerPositionInfoMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerPositionInfoMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CURPOS_FIELD_NUMBER = 1;
    private com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg curPos_;
    /**
     * <code>optional .PostionMsg curPos = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    public boolean hasCurPos() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .PostionMsg curPos = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    public com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg getCurPos() {
      return curPos_;
    }
    /**
     * <code>optional .PostionMsg curPos = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    public com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder getCurPosOrBuilder() {
      return curPos_;
    }

    public static final int PREPOS_FIELD_NUMBER = 2;
    private com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg prePos_;
    /**
     * <code>optional .PostionMsg prePos = 2;</code>
     *
     * <pre>
     *上一次记录位置
     * </pre>
     */
    public boolean hasPrePos() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .PostionMsg prePos = 2;</code>
     *
     * <pre>
     *上一次记录位置
     * </pre>
     */
    public com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg getPrePos() {
      return prePos_;
    }
    /**
     * <code>optional .PostionMsg prePos = 2;</code>
     *
     * <pre>
     *上一次记录位置
     * </pre>
     */
    public com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder getPrePosOrBuilder() {
      return prePos_;
    }

    private void initFields() {
      curPos_ = com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.getDefaultInstance();
      prePos_ = com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, curPos_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, prePos_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, curPos_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, prePos_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerPositionInfoMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerPositionInfoMsg)
        com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.empire.protocol.pb.army.PlayerPositionInfoProto.internal_static_PlayerPositionInfoMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.empire.protocol.pb.army.PlayerPositionInfoProto.internal_static_PlayerPositionInfoMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg.class, com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg.Builder.class);
      }

      // Construct using com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCurPosFieldBuilder();
          getPrePosFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (curPosBuilder_ == null) {
          curPos_ = com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.getDefaultInstance();
        } else {
          curPosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (prePosBuilder_ == null) {
          prePos_ = com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.getDefaultInstance();
        } else {
          prePosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.empire.protocol.pb.army.PlayerPositionInfoProto.internal_static_PlayerPositionInfoMsg_descriptor;
      }

      public com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg getDefaultInstanceForType() {
        return com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg.getDefaultInstance();
      }

      public com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg build() {
        com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg buildPartial() {
        com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg result = new com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (curPosBuilder_ == null) {
          result.curPos_ = curPos_;
        } else {
          result.curPos_ = curPosBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (prePosBuilder_ == null) {
          result.prePos_ = prePos_;
        } else {
          result.prePos_ = prePosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg) {
          return mergeFrom((com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg other) {
        if (other == com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg.getDefaultInstance()) return this;
        if (other.hasCurPos()) {
          mergeCurPos(other.getCurPos());
        }
        if (other.hasPrePos()) {
          mergePrePos(other.getPrePos());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.app.empire.protocol.pb.army.PlayerPositionInfoProto.PlayerPositionInfoMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg curPos_ = com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder> curPosBuilder_;
      /**
       * <code>optional .PostionMsg curPos = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public boolean hasCurPos() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .PostionMsg curPos = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg getCurPos() {
        if (curPosBuilder_ == null) {
          return curPos_;
        } else {
          return curPosBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PostionMsg curPos = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public Builder setCurPos(com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg value) {
        if (curPosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          curPos_ = value;
          onChanged();
        } else {
          curPosBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PostionMsg curPos = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public Builder setCurPos(
          com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder builderForValue) {
        if (curPosBuilder_ == null) {
          curPos_ = builderForValue.build();
          onChanged();
        } else {
          curPosBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PostionMsg curPos = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public Builder mergeCurPos(com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg value) {
        if (curPosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              curPos_ != com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.getDefaultInstance()) {
            curPos_ =
              com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.newBuilder(curPos_).mergeFrom(value).buildPartial();
          } else {
            curPos_ = value;
          }
          onChanged();
        } else {
          curPosBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PostionMsg curPos = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public Builder clearCurPos() {
        if (curPosBuilder_ == null) {
          curPos_ = com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.getDefaultInstance();
          onChanged();
        } else {
          curPosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .PostionMsg curPos = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder getCurPosBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCurPosFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PostionMsg curPos = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder getCurPosOrBuilder() {
        if (curPosBuilder_ != null) {
          return curPosBuilder_.getMessageOrBuilder();
        } else {
          return curPos_;
        }
      }
      /**
       * <code>optional .PostionMsg curPos = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder> 
          getCurPosFieldBuilder() {
        if (curPosBuilder_ == null) {
          curPosBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder>(
                  getCurPos(),
                  getParentForChildren(),
                  isClean());
          curPos_ = null;
        }
        return curPosBuilder_;
      }

      private com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg prePos_ = com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder> prePosBuilder_;
      /**
       * <code>optional .PostionMsg prePos = 2;</code>
       *
       * <pre>
       *上一次记录位置
       * </pre>
       */
      public boolean hasPrePos() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .PostionMsg prePos = 2;</code>
       *
       * <pre>
       *上一次记录位置
       * </pre>
       */
      public com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg getPrePos() {
        if (prePosBuilder_ == null) {
          return prePos_;
        } else {
          return prePosBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PostionMsg prePos = 2;</code>
       *
       * <pre>
       *上一次记录位置
       * </pre>
       */
      public Builder setPrePos(com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg value) {
        if (prePosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          prePos_ = value;
          onChanged();
        } else {
          prePosBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .PostionMsg prePos = 2;</code>
       *
       * <pre>
       *上一次记录位置
       * </pre>
       */
      public Builder setPrePos(
          com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder builderForValue) {
        if (prePosBuilder_ == null) {
          prePos_ = builderForValue.build();
          onChanged();
        } else {
          prePosBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .PostionMsg prePos = 2;</code>
       *
       * <pre>
       *上一次记录位置
       * </pre>
       */
      public Builder mergePrePos(com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg value) {
        if (prePosBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              prePos_ != com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.getDefaultInstance()) {
            prePos_ =
              com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.newBuilder(prePos_).mergeFrom(value).buildPartial();
          } else {
            prePos_ = value;
          }
          onChanged();
        } else {
          prePosBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .PostionMsg prePos = 2;</code>
       *
       * <pre>
       *上一次记录位置
       * </pre>
       */
      public Builder clearPrePos() {
        if (prePosBuilder_ == null) {
          prePos_ = com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.getDefaultInstance();
          onChanged();
        } else {
          prePosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .PostionMsg prePos = 2;</code>
       *
       * <pre>
       *上一次记录位置
       * </pre>
       */
      public com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder getPrePosBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPrePosFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PostionMsg prePos = 2;</code>
       *
       * <pre>
       *上一次记录位置
       * </pre>
       */
      public com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder getPrePosOrBuilder() {
        if (prePosBuilder_ != null) {
          return prePosBuilder_.getMessageOrBuilder();
        } else {
          return prePos_;
        }
      }
      /**
       * <code>optional .PostionMsg prePos = 2;</code>
       *
       * <pre>
       *上一次记录位置
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder> 
          getPrePosFieldBuilder() {
        if (prePosBuilder_ == null) {
          prePosBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsg.Builder, com.app.empire.protocol.pb.warField.PostionMsgProto.PostionMsgOrBuilder>(
                  getPrePos(),
                  getParentForChildren(),
                  isClean());
          prePos_ = null;
        }
        return prePosBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PlayerPositionInfoMsg)
    }

    static {
      defaultInstance = new PlayerPositionInfoMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerPositionInfoMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerPositionInfoMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerPositionInfoMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n army/PlayerPositionInfoMsg.proto\032\031warF" +
      "ield/PostionMsg.proto\"Q\n\025PlayerPositionI" +
      "nfoMsg\022\033\n\006curPos\030\001 \001(\0132\013.PostionMsg\022\033\n\006p" +
      "rePos\030\002 \001(\0132\013.PostionMsgB:\n\037com.app.empi" +
      "re.protocol.pb.armyB\027PlayerPositionInfoP" +
      "roto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.app.empire.protocol.pb.warField.PostionMsgProto.getDescriptor(),
        }, assigner);
    internal_static_PlayerPositionInfoMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerPositionInfoMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerPositionInfoMsg_descriptor,
        new java.lang.String[] { "CurPos", "PrePos", });
    com.app.empire.protocol.pb.warField.PostionMsgProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
