// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scene/PlayerMoveSyncMsg.proto

package com.app.empire.protocol.pb.scene;

public final class PlayerMoveSyncProto {
  private PlayerMoveSyncProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerMoveSyncMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerMoveSyncMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .PBVector3 cur = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    boolean hasCur();
    /**
     * <code>optional .PBVector3 cur = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3 getCur();
    /**
     * <code>optional .PBVector3 cur = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3OrBuilder getCurOrBuilder();
  }
  /**
   * Protobuf type {@code PlayerMoveSyncMsg}
   */
  public static final class PlayerMoveSyncMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PlayerMoveSyncMsg)
      PlayerMoveSyncMsgOrBuilder {
    // Use PlayerMoveSyncMsg.newBuilder() to construct.
    private PlayerMoveSyncMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerMoveSyncMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerMoveSyncMsg defaultInstance;
    public static PlayerMoveSyncMsg getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerMoveSyncMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerMoveSyncMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = cur_.toBuilder();
              }
              cur_ = input.readMessage(com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cur_);
                cur_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.internal_static_PlayerMoveSyncMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.internal_static_PlayerMoveSyncMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg.class, com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerMoveSyncMsg> PARSER =
        new com.google.protobuf.AbstractParser<PlayerMoveSyncMsg>() {
      public PlayerMoveSyncMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerMoveSyncMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerMoveSyncMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CUR_FIELD_NUMBER = 1;
    private com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3 cur_;
    /**
     * <code>optional .PBVector3 cur = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    public boolean hasCur() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .PBVector3 cur = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    public com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3 getCur() {
      return cur_;
    }
    /**
     * <code>optional .PBVector3 cur = 1;</code>
     *
     * <pre>
     *当前位置
     * </pre>
     */
    public com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3OrBuilder getCurOrBuilder() {
      return cur_;
    }

    private void initFields() {
      cur_ = com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, cur_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cur_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerMoveSyncMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerMoveSyncMsg)
        com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.internal_static_PlayerMoveSyncMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.internal_static_PlayerMoveSyncMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg.class, com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg.Builder.class);
      }

      // Construct using com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCurFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (curBuilder_ == null) {
          cur_ = com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.getDefaultInstance();
        } else {
          curBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.internal_static_PlayerMoveSyncMsg_descriptor;
      }

      public com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg getDefaultInstanceForType() {
        return com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg.getDefaultInstance();
      }

      public com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg build() {
        com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg buildPartial() {
        com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg result = new com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (curBuilder_ == null) {
          result.cur_ = cur_;
        } else {
          result.cur_ = curBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg) {
          return mergeFrom((com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg other) {
        if (other == com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg.getDefaultInstance()) return this;
        if (other.hasCur()) {
          mergeCur(other.getCur());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.app.empire.protocol.pb.scene.PlayerMoveSyncProto.PlayerMoveSyncMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3 cur_ = com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3, com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.Builder, com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3OrBuilder> curBuilder_;
      /**
       * <code>optional .PBVector3 cur = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public boolean hasCur() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .PBVector3 cur = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3 getCur() {
        if (curBuilder_ == null) {
          return cur_;
        } else {
          return curBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PBVector3 cur = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public Builder setCur(com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3 value) {
        if (curBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cur_ = value;
          onChanged();
        } else {
          curBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PBVector3 cur = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public Builder setCur(
          com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.Builder builderForValue) {
        if (curBuilder_ == null) {
          cur_ = builderForValue.build();
          onChanged();
        } else {
          curBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PBVector3 cur = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public Builder mergeCur(com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3 value) {
        if (curBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              cur_ != com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.getDefaultInstance()) {
            cur_ =
              com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.newBuilder(cur_).mergeFrom(value).buildPartial();
          } else {
            cur_ = value;
          }
          onChanged();
        } else {
          curBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PBVector3 cur = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public Builder clearCur() {
        if (curBuilder_ == null) {
          cur_ = com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.getDefaultInstance();
          onChanged();
        } else {
          curBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .PBVector3 cur = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.Builder getCurBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCurFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PBVector3 cur = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      public com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3OrBuilder getCurOrBuilder() {
        if (curBuilder_ != null) {
          return curBuilder_.getMessageOrBuilder();
        } else {
          return cur_;
        }
      }
      /**
       * <code>optional .PBVector3 cur = 1;</code>
       *
       * <pre>
       *当前位置
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3, com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.Builder, com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3OrBuilder> 
          getCurFieldBuilder() {
        if (curBuilder_ == null) {
          curBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3, com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3.Builder, com.app.empire.protocol.pb.warField.Vector3Proto.PBVector3OrBuilder>(
                  getCur(),
                  getParentForChildren(),
                  isClean());
          cur_ = null;
        }
        return curBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PlayerMoveSyncMsg)
    }

    static {
      defaultInstance = new PlayerMoveSyncMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerMoveSyncMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerMoveSyncMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerMoveSyncMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035scene/PlayerMoveSyncMsg.proto\032\030warFiel" +
      "d/PBVector3.proto\",\n\021PlayerMoveSyncMsg\022\027" +
      "\n\003cur\030\001 \001(\0132\n.PBVector3B7\n com.app.empir" +
      "e.protocol.pb.sceneB\023PlayerMoveSyncProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.app.empire.protocol.pb.warField.Vector3Proto.getDescriptor(),
        }, assigner);
    internal_static_PlayerMoveSyncMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerMoveSyncMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerMoveSyncMsg_descriptor,
        new java.lang.String[] { "Cur", });
    com.app.empire.protocol.pb.warField.Vector3Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
