// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battle/DamageListMsg.proto

package com.app.empire.protocol.pb.battle;

public final class DamageListMsgProtocol {
  private DamageListMsgProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DamageListMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DamageListMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 attackId = 1;</code>
     *
     * <pre>
     *攻击唯一ID
     * </pre>
     */
    boolean hasAttackId();
    /**
     * <code>optional int64 attackId = 1;</code>
     *
     * <pre>
     *攻击唯一ID
     * </pre>
     */
    long getAttackId();

    /**
     * <code>repeated .DamageMsg damages = 2;</code>
     *
     * <pre>
     *伤害
     * </pre>
     */
    java.util.List<com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg> 
        getDamagesList();
    /**
     * <code>repeated .DamageMsg damages = 2;</code>
     *
     * <pre>
     *伤害
     * </pre>
     */
    com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg getDamages(int index);
    /**
     * <code>repeated .DamageMsg damages = 2;</code>
     *
     * <pre>
     *伤害
     * </pre>
     */
    int getDamagesCount();
    /**
     * <code>repeated .DamageMsg damages = 2;</code>
     *
     * <pre>
     *伤害
     * </pre>
     */
    java.util.List<? extends com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsgOrBuilder> 
        getDamagesOrBuilderList();
    /**
     * <code>repeated .DamageMsg damages = 2;</code>
     *
     * <pre>
     *伤害
     * </pre>
     */
    com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsgOrBuilder getDamagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DamageListMsg}
   */
  public static final class DamageListMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DamageListMsg)
      DamageListMsgOrBuilder {
    // Use DamageListMsg.newBuilder() to construct.
    private DamageListMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DamageListMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DamageListMsg defaultInstance;
    public static DamageListMsg getDefaultInstance() {
      return defaultInstance;
    }

    public DamageListMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DamageListMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              attackId_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                damages_ = new java.util.ArrayList<com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg>();
                mutable_bitField0_ |= 0x00000002;
              }
              damages_.add(input.readMessage(com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          damages_ = java.util.Collections.unmodifiableList(damages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.empire.protocol.pb.battle.DamageListMsgProtocol.internal_static_DamageListMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.empire.protocol.pb.battle.DamageListMsgProtocol.internal_static_DamageListMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg.class, com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<DamageListMsg> PARSER =
        new com.google.protobuf.AbstractParser<DamageListMsg>() {
      public DamageListMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DamageListMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DamageListMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ATTACKID_FIELD_NUMBER = 1;
    private long attackId_;
    /**
     * <code>optional int64 attackId = 1;</code>
     *
     * <pre>
     *攻击唯一ID
     * </pre>
     */
    public boolean hasAttackId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 attackId = 1;</code>
     *
     * <pre>
     *攻击唯一ID
     * </pre>
     */
    public long getAttackId() {
      return attackId_;
    }

    public static final int DAMAGES_FIELD_NUMBER = 2;
    private java.util.List<com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg> damages_;
    /**
     * <code>repeated .DamageMsg damages = 2;</code>
     *
     * <pre>
     *伤害
     * </pre>
     */
    public java.util.List<com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg> getDamagesList() {
      return damages_;
    }
    /**
     * <code>repeated .DamageMsg damages = 2;</code>
     *
     * <pre>
     *伤害
     * </pre>
     */
    public java.util.List<? extends com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsgOrBuilder> 
        getDamagesOrBuilderList() {
      return damages_;
    }
    /**
     * <code>repeated .DamageMsg damages = 2;</code>
     *
     * <pre>
     *伤害
     * </pre>
     */
    public int getDamagesCount() {
      return damages_.size();
    }
    /**
     * <code>repeated .DamageMsg damages = 2;</code>
     *
     * <pre>
     *伤害
     * </pre>
     */
    public com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg getDamages(int index) {
      return damages_.get(index);
    }
    /**
     * <code>repeated .DamageMsg damages = 2;</code>
     *
     * <pre>
     *伤害
     * </pre>
     */
    public com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsgOrBuilder getDamagesOrBuilder(
        int index) {
      return damages_.get(index);
    }

    private void initFields() {
      attackId_ = 0L;
      damages_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, attackId_);
      }
      for (int i = 0; i < damages_.size(); i++) {
        output.writeMessage(2, damages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, attackId_);
      }
      for (int i = 0; i < damages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, damages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DamageListMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DamageListMsg)
        com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.empire.protocol.pb.battle.DamageListMsgProtocol.internal_static_DamageListMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.empire.protocol.pb.battle.DamageListMsgProtocol.internal_static_DamageListMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg.class, com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg.Builder.class);
      }

      // Construct using com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDamagesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        attackId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (damagesBuilder_ == null) {
          damages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          damagesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.empire.protocol.pb.battle.DamageListMsgProtocol.internal_static_DamageListMsg_descriptor;
      }

      public com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg getDefaultInstanceForType() {
        return com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg.getDefaultInstance();
      }

      public com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg build() {
        com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg buildPartial() {
        com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg result = new com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.attackId_ = attackId_;
        if (damagesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            damages_ = java.util.Collections.unmodifiableList(damages_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.damages_ = damages_;
        } else {
          result.damages_ = damagesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg) {
          return mergeFrom((com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg other) {
        if (other == com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg.getDefaultInstance()) return this;
        if (other.hasAttackId()) {
          setAttackId(other.getAttackId());
        }
        if (damagesBuilder_ == null) {
          if (!other.damages_.isEmpty()) {
            if (damages_.isEmpty()) {
              damages_ = other.damages_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureDamagesIsMutable();
              damages_.addAll(other.damages_);
            }
            onChanged();
          }
        } else {
          if (!other.damages_.isEmpty()) {
            if (damagesBuilder_.isEmpty()) {
              damagesBuilder_.dispose();
              damagesBuilder_ = null;
              damages_ = other.damages_;
              bitField0_ = (bitField0_ & ~0x00000002);
              damagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDamagesFieldBuilder() : null;
            } else {
              damagesBuilder_.addAllMessages(other.damages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.app.empire.protocol.pb.battle.DamageListMsgProtocol.DamageListMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long attackId_ ;
      /**
       * <code>optional int64 attackId = 1;</code>
       *
       * <pre>
       *攻击唯一ID
       * </pre>
       */
      public boolean hasAttackId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 attackId = 1;</code>
       *
       * <pre>
       *攻击唯一ID
       * </pre>
       */
      public long getAttackId() {
        return attackId_;
      }
      /**
       * <code>optional int64 attackId = 1;</code>
       *
       * <pre>
       *攻击唯一ID
       * </pre>
       */
      public Builder setAttackId(long value) {
        bitField0_ |= 0x00000001;
        attackId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 attackId = 1;</code>
       *
       * <pre>
       *攻击唯一ID
       * </pre>
       */
      public Builder clearAttackId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        attackId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg> damages_ =
        java.util.Collections.emptyList();
      private void ensureDamagesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          damages_ = new java.util.ArrayList<com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg>(damages_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.Builder, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsgOrBuilder> damagesBuilder_;

      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public java.util.List<com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg> getDamagesList() {
        if (damagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(damages_);
        } else {
          return damagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public int getDamagesCount() {
        if (damagesBuilder_ == null) {
          return damages_.size();
        } else {
          return damagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg getDamages(int index) {
        if (damagesBuilder_ == null) {
          return damages_.get(index);
        } else {
          return damagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public Builder setDamages(
          int index, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg value) {
        if (damagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDamagesIsMutable();
          damages_.set(index, value);
          onChanged();
        } else {
          damagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public Builder setDamages(
          int index, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.Builder builderForValue) {
        if (damagesBuilder_ == null) {
          ensureDamagesIsMutable();
          damages_.set(index, builderForValue.build());
          onChanged();
        } else {
          damagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public Builder addDamages(com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg value) {
        if (damagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDamagesIsMutable();
          damages_.add(value);
          onChanged();
        } else {
          damagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public Builder addDamages(
          int index, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg value) {
        if (damagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDamagesIsMutable();
          damages_.add(index, value);
          onChanged();
        } else {
          damagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public Builder addDamages(
          com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.Builder builderForValue) {
        if (damagesBuilder_ == null) {
          ensureDamagesIsMutable();
          damages_.add(builderForValue.build());
          onChanged();
        } else {
          damagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public Builder addDamages(
          int index, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.Builder builderForValue) {
        if (damagesBuilder_ == null) {
          ensureDamagesIsMutable();
          damages_.add(index, builderForValue.build());
          onChanged();
        } else {
          damagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public Builder addAllDamages(
          java.lang.Iterable<? extends com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg> values) {
        if (damagesBuilder_ == null) {
          ensureDamagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, damages_);
          onChanged();
        } else {
          damagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public Builder clearDamages() {
        if (damagesBuilder_ == null) {
          damages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          damagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public Builder removeDamages(int index) {
        if (damagesBuilder_ == null) {
          ensureDamagesIsMutable();
          damages_.remove(index);
          onChanged();
        } else {
          damagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.Builder getDamagesBuilder(
          int index) {
        return getDamagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsgOrBuilder getDamagesOrBuilder(
          int index) {
        if (damagesBuilder_ == null) {
          return damages_.get(index);  } else {
          return damagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public java.util.List<? extends com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsgOrBuilder> 
           getDamagesOrBuilderList() {
        if (damagesBuilder_ != null) {
          return damagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(damages_);
        }
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.Builder addDamagesBuilder() {
        return getDamagesFieldBuilder().addBuilder(
            com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.Builder addDamagesBuilder(
          int index) {
        return getDamagesFieldBuilder().addBuilder(
            index, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .DamageMsg damages = 2;</code>
       *
       * <pre>
       *伤害
       * </pre>
       */
      public java.util.List<com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.Builder> 
           getDamagesBuilderList() {
        return getDamagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.Builder, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsgOrBuilder> 
          getDamagesFieldBuilder() {
        if (damagesBuilder_ == null) {
          damagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsg.Builder, com.app.empire.protocol.pb.battle.DamageMsgProto.DamageMsgOrBuilder>(
                  damages_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          damages_ = null;
        }
        return damagesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DamageListMsg)
    }

    static {
      defaultInstance = new DamageListMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DamageListMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DamageListMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DamageListMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032battle/DamageListMsg.proto\032\026battle/Dam" +
      "ageMsg.proto\">\n\rDamageListMsg\022\020\n\010attackI" +
      "d\030\001 \001(\003\022\033\n\007damages\030\002 \003(\0132\n.DamageMsgB:\n!" +
      "com.app.empire.protocol.pb.battleB\025Damag" +
      "eListMsgProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.app.empire.protocol.pb.battle.DamageMsgProto.getDescriptor(),
        }, assigner);
    internal_static_DamageListMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DamageListMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DamageListMsg_descriptor,
        new java.lang.String[] { "AttackId", "Damages", });
    com.app.empire.protocol.pb.battle.DamageMsgProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
