// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battle/SnareOptionMsg.proto

package com.app.empire.protocol.pb.battle;

public final class SnareOptionMsgProto {
  private SnareOptionMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SnareOptionMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SnareOptionMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *操作类型 1 进入陷阱，2 退出陷阱
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *操作类型 1 进入陷阱，2 退出陷阱
     * </pre>
     */
    int getType();

    /**
     * <code>required int64 livingId = 2;</code>
     *
     * <pre>
     *陷阱ID
     * </pre>
     */
    boolean hasLivingId();
    /**
     * <code>required int64 livingId = 2;</code>
     *
     * <pre>
     *陷阱ID
     * </pre>
     */
    long getLivingId();

    /**
     * <code>required int64 injuredId = 3;</code>
     *
     * <pre>
     *受伤者ID
     * </pre>
     */
    boolean hasInjuredId();
    /**
     * <code>required int64 injuredId = 3;</code>
     *
     * <pre>
     *受伤者ID
     * </pre>
     */
    long getInjuredId();
  }
  /**
   * Protobuf type {@code SnareOptionMsg}
   */
  public static final class SnareOptionMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SnareOptionMsg)
      SnareOptionMsgOrBuilder {
    // Use SnareOptionMsg.newBuilder() to construct.
    private SnareOptionMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SnareOptionMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SnareOptionMsg defaultInstance;
    public static SnareOptionMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SnareOptionMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SnareOptionMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              livingId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              injuredId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.empire.protocol.pb.battle.SnareOptionMsgProto.internal_static_SnareOptionMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.empire.protocol.pb.battle.SnareOptionMsgProto.internal_static_SnareOptionMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg.class, com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SnareOptionMsg> PARSER =
        new com.google.protobuf.AbstractParser<SnareOptionMsg>() {
      public SnareOptionMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SnareOptionMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SnareOptionMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *操作类型 1 进入陷阱，2 退出陷阱
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *操作类型 1 进入陷阱，2 退出陷阱
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int LIVINGID_FIELD_NUMBER = 2;
    private long livingId_;
    /**
     * <code>required int64 livingId = 2;</code>
     *
     * <pre>
     *陷阱ID
     * </pre>
     */
    public boolean hasLivingId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 livingId = 2;</code>
     *
     * <pre>
     *陷阱ID
     * </pre>
     */
    public long getLivingId() {
      return livingId_;
    }

    public static final int INJUREDID_FIELD_NUMBER = 3;
    private long injuredId_;
    /**
     * <code>required int64 injuredId = 3;</code>
     *
     * <pre>
     *受伤者ID
     * </pre>
     */
    public boolean hasInjuredId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 injuredId = 3;</code>
     *
     * <pre>
     *受伤者ID
     * </pre>
     */
    public long getInjuredId() {
      return injuredId_;
    }

    private void initFields() {
      type_ = 0;
      livingId_ = 0L;
      injuredId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLivingId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInjuredId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, livingId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, injuredId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, livingId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, injuredId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SnareOptionMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SnareOptionMsg)
        com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.empire.protocol.pb.battle.SnareOptionMsgProto.internal_static_SnareOptionMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.empire.protocol.pb.battle.SnareOptionMsgProto.internal_static_SnareOptionMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg.class, com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg.Builder.class);
      }

      // Construct using com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        livingId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        injuredId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.empire.protocol.pb.battle.SnareOptionMsgProto.internal_static_SnareOptionMsg_descriptor;
      }

      public com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg getDefaultInstanceForType() {
        return com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg.getDefaultInstance();
      }

      public com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg build() {
        com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg buildPartial() {
        com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg result = new com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.livingId_ = livingId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.injuredId_ = injuredId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg) {
          return mergeFrom((com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg other) {
        if (other == com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLivingId()) {
          setLivingId(other.getLivingId());
        }
        if (other.hasInjuredId()) {
          setInjuredId(other.getInjuredId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasLivingId()) {
          
          return false;
        }
        if (!hasInjuredId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.app.empire.protocol.pb.battle.SnareOptionMsgProto.SnareOptionMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *操作类型 1 进入陷阱，2 退出陷阱
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *操作类型 1 进入陷阱，2 退出陷阱
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *操作类型 1 进入陷阱，2 退出陷阱
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *操作类型 1 进入陷阱，2 退出陷阱
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private long livingId_ ;
      /**
       * <code>required int64 livingId = 2;</code>
       *
       * <pre>
       *陷阱ID
       * </pre>
       */
      public boolean hasLivingId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 livingId = 2;</code>
       *
       * <pre>
       *陷阱ID
       * </pre>
       */
      public long getLivingId() {
        return livingId_;
      }
      /**
       * <code>required int64 livingId = 2;</code>
       *
       * <pre>
       *陷阱ID
       * </pre>
       */
      public Builder setLivingId(long value) {
        bitField0_ |= 0x00000002;
        livingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 livingId = 2;</code>
       *
       * <pre>
       *陷阱ID
       * </pre>
       */
      public Builder clearLivingId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        livingId_ = 0L;
        onChanged();
        return this;
      }

      private long injuredId_ ;
      /**
       * <code>required int64 injuredId = 3;</code>
       *
       * <pre>
       *受伤者ID
       * </pre>
       */
      public boolean hasInjuredId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 injuredId = 3;</code>
       *
       * <pre>
       *受伤者ID
       * </pre>
       */
      public long getInjuredId() {
        return injuredId_;
      }
      /**
       * <code>required int64 injuredId = 3;</code>
       *
       * <pre>
       *受伤者ID
       * </pre>
       */
      public Builder setInjuredId(long value) {
        bitField0_ |= 0x00000004;
        injuredId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 injuredId = 3;</code>
       *
       * <pre>
       *受伤者ID
       * </pre>
       */
      public Builder clearInjuredId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        injuredId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SnareOptionMsg)
    }

    static {
      defaultInstance = new SnareOptionMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SnareOptionMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SnareOptionMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SnareOptionMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033battle/SnareOptionMsg.proto\"C\n\016SnareOp" +
      "tionMsg\022\014\n\004type\030\001 \002(\005\022\020\n\010livingId\030\002 \002(\003\022" +
      "\021\n\tinjuredId\030\003 \002(\003B8\n!com.app.empire.pro" +
      "tocol.pb.battleB\023SnareOptionMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SnareOptionMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SnareOptionMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SnareOptionMsg_descriptor,
        new java.lang.String[] { "Type", "LivingId", "InjuredId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
