// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drop/DropPickupResultMsg.proto

package com.app.empire.protocol.pb.drop;

public final class DropPickupResultProto {
  private DropPickupResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DropPickupResultMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DropPickupResultMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 packageId = 1;</code>
     *
     * <pre>
     * 掉落包ID
     * </pre>
     */
    boolean hasPackageId();
    /**
     * <code>optional int32 packageId = 1;</code>
     *
     * <pre>
     * 掉落包ID
     * </pre>
     */
    int getPackageId();

    /**
     * <code>optional int64 dropItemId = 2;</code>
     *
     * <pre>
     * 掉落物ID
     * </pre>
     */
    boolean hasDropItemId();
    /**
     * <code>optional int64 dropItemId = 2;</code>
     *
     * <pre>
     * 掉落物ID
     * </pre>
     */
    long getDropItemId();

    /**
     * <code>optional bool result = 3;</code>
     */
    boolean hasResult();
    /**
     * <code>optional bool result = 3;</code>
     */
    boolean getResult();
  }
  /**
   * Protobuf type {@code DropPickupResultMsg}
   */
  public static final class DropPickupResultMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DropPickupResultMsg)
      DropPickupResultMsgOrBuilder {
    // Use DropPickupResultMsg.newBuilder() to construct.
    private DropPickupResultMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DropPickupResultMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DropPickupResultMsg defaultInstance;
    public static DropPickupResultMsg getDefaultInstance() {
      return defaultInstance;
    }

    public DropPickupResultMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DropPickupResultMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              packageId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              dropItemId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              result_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.empire.protocol.pb.drop.DropPickupResultProto.internal_static_DropPickupResultMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.empire.protocol.pb.drop.DropPickupResultProto.internal_static_DropPickupResultMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg.class, com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<DropPickupResultMsg> PARSER =
        new com.google.protobuf.AbstractParser<DropPickupResultMsg>() {
      public DropPickupResultMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DropPickupResultMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DropPickupResultMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PACKAGEID_FIELD_NUMBER = 1;
    private int packageId_;
    /**
     * <code>optional int32 packageId = 1;</code>
     *
     * <pre>
     * 掉落包ID
     * </pre>
     */
    public boolean hasPackageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 packageId = 1;</code>
     *
     * <pre>
     * 掉落包ID
     * </pre>
     */
    public int getPackageId() {
      return packageId_;
    }

    public static final int DROPITEMID_FIELD_NUMBER = 2;
    private long dropItemId_;
    /**
     * <code>optional int64 dropItemId = 2;</code>
     *
     * <pre>
     * 掉落物ID
     * </pre>
     */
    public boolean hasDropItemId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 dropItemId = 2;</code>
     *
     * <pre>
     * 掉落物ID
     * </pre>
     */
    public long getDropItemId() {
      return dropItemId_;
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private boolean result_;
    /**
     * <code>optional bool result = 3;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool result = 3;</code>
     */
    public boolean getResult() {
      return result_;
    }

    private void initFields() {
      packageId_ = 0;
      dropItemId_ = 0L;
      result_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, packageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, dropItemId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, packageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, dropItemId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DropPickupResultMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DropPickupResultMsg)
        com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.empire.protocol.pb.drop.DropPickupResultProto.internal_static_DropPickupResultMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.empire.protocol.pb.drop.DropPickupResultProto.internal_static_DropPickupResultMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg.class, com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg.Builder.class);
      }

      // Construct using com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        packageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dropItemId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.empire.protocol.pb.drop.DropPickupResultProto.internal_static_DropPickupResultMsg_descriptor;
      }

      public com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg getDefaultInstanceForType() {
        return com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg.getDefaultInstance();
      }

      public com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg build() {
        com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg buildPartial() {
        com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg result = new com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.packageId_ = packageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dropItemId_ = dropItemId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg) {
          return mergeFrom((com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg other) {
        if (other == com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg.getDefaultInstance()) return this;
        if (other.hasPackageId()) {
          setPackageId(other.getPackageId());
        }
        if (other.hasDropItemId()) {
          setDropItemId(other.getDropItemId());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.app.empire.protocol.pb.drop.DropPickupResultProto.DropPickupResultMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int packageId_ ;
      /**
       * <code>optional int32 packageId = 1;</code>
       *
       * <pre>
       * 掉落包ID
       * </pre>
       */
      public boolean hasPackageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 packageId = 1;</code>
       *
       * <pre>
       * 掉落包ID
       * </pre>
       */
      public int getPackageId() {
        return packageId_;
      }
      /**
       * <code>optional int32 packageId = 1;</code>
       *
       * <pre>
       * 掉落包ID
       * </pre>
       */
      public Builder setPackageId(int value) {
        bitField0_ |= 0x00000001;
        packageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 packageId = 1;</code>
       *
       * <pre>
       * 掉落包ID
       * </pre>
       */
      public Builder clearPackageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        packageId_ = 0;
        onChanged();
        return this;
      }

      private long dropItemId_ ;
      /**
       * <code>optional int64 dropItemId = 2;</code>
       *
       * <pre>
       * 掉落物ID
       * </pre>
       */
      public boolean hasDropItemId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 dropItemId = 2;</code>
       *
       * <pre>
       * 掉落物ID
       * </pre>
       */
      public long getDropItemId() {
        return dropItemId_;
      }
      /**
       * <code>optional int64 dropItemId = 2;</code>
       *
       * <pre>
       * 掉落物ID
       * </pre>
       */
      public Builder setDropItemId(long value) {
        bitField0_ |= 0x00000002;
        dropItemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 dropItemId = 2;</code>
       *
       * <pre>
       * 掉落物ID
       * </pre>
       */
      public Builder clearDropItemId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dropItemId_ = 0L;
        onChanged();
        return this;
      }

      private boolean result_ ;
      /**
       * <code>optional bool result = 3;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool result = 3;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>optional bool result = 3;</code>
       */
      public Builder setResult(boolean value) {
        bitField0_ |= 0x00000004;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool result = 3;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000004);
        result_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DropPickupResultMsg)
    }

    static {
      defaultInstance = new DropPickupResultMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DropPickupResultMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DropPickupResultMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DropPickupResultMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036drop/DropPickupResultMsg.proto\"L\n\023Drop" +
      "PickupResultMsg\022\021\n\tpackageId\030\001 \001(\005\022\022\n\ndr" +
      "opItemId\030\002 \001(\003\022\016\n\006result\030\003 \001(\010B8\n\037com.ap" +
      "p.empire.protocol.pb.dropB\025DropPickupRes" +
      "ultProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DropPickupResultMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DropPickupResultMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DropPickupResultMsg_descriptor,
        new java.lang.String[] { "PackageId", "DropItemId", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
