// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player/PlayerAttUpdateMsg.proto

package com.app.empire.protocol.pb.player;

public final class PlayerAttUpdateProto {
  private PlayerAttUpdateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerAttUpdateMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerAttUpdateMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 playerId = 1;</code>
     *
     * <pre>
     *角色ID
     * </pre>
     */
    boolean hasPlayerId();
    /**
     * <code>required int64 playerId = 1;</code>
     *
     * <pre>
     *角色ID
     * </pre>
     */
    long getPlayerId();

    /**
     * <code>repeated .PropertyMsg att = 2;</code>
     *
     * <pre>
     *需要更新的属性
     * </pre>
     */
    java.util.List<com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg> 
        getAttList();
    /**
     * <code>repeated .PropertyMsg att = 2;</code>
     *
     * <pre>
     *需要更新的属性
     * </pre>
     */
    com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg getAtt(int index);
    /**
     * <code>repeated .PropertyMsg att = 2;</code>
     *
     * <pre>
     *需要更新的属性
     * </pre>
     */
    int getAttCount();
    /**
     * <code>repeated .PropertyMsg att = 2;</code>
     *
     * <pre>
     *需要更新的属性
     * </pre>
     */
    java.util.List<? extends com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsgOrBuilder> 
        getAttOrBuilderList();
    /**
     * <code>repeated .PropertyMsg att = 2;</code>
     *
     * <pre>
     *需要更新的属性
     * </pre>
     */
    com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsgOrBuilder getAttOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PlayerAttUpdateMsg}
   *
   * <pre>
   *单个角色属性的更新
   * </pre>
   */
  public static final class PlayerAttUpdateMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PlayerAttUpdateMsg)
      PlayerAttUpdateMsgOrBuilder {
    // Use PlayerAttUpdateMsg.newBuilder() to construct.
    private PlayerAttUpdateMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerAttUpdateMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerAttUpdateMsg defaultInstance;
    public static PlayerAttUpdateMsg getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerAttUpdateMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerAttUpdateMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerId_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                att_ = new java.util.ArrayList<com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg>();
                mutable_bitField0_ |= 0x00000002;
              }
              att_.add(input.readMessage(com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          att_ = java.util.Collections.unmodifiableList(att_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.empire.protocol.pb.player.PlayerAttUpdateProto.internal_static_PlayerAttUpdateMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.empire.protocol.pb.player.PlayerAttUpdateProto.internal_static_PlayerAttUpdateMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg.class, com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerAttUpdateMsg> PARSER =
        new com.google.protobuf.AbstractParser<PlayerAttUpdateMsg>() {
      public PlayerAttUpdateMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerAttUpdateMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerAttUpdateMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>required int64 playerId = 1;</code>
     *
     * <pre>
     *角色ID
     * </pre>
     */
    public boolean hasPlayerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 playerId = 1;</code>
     *
     * <pre>
     *角色ID
     * </pre>
     */
    public long getPlayerId() {
      return playerId_;
    }

    public static final int ATT_FIELD_NUMBER = 2;
    private java.util.List<com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg> att_;
    /**
     * <code>repeated .PropertyMsg att = 2;</code>
     *
     * <pre>
     *需要更新的属性
     * </pre>
     */
    public java.util.List<com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg> getAttList() {
      return att_;
    }
    /**
     * <code>repeated .PropertyMsg att = 2;</code>
     *
     * <pre>
     *需要更新的属性
     * </pre>
     */
    public java.util.List<? extends com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsgOrBuilder> 
        getAttOrBuilderList() {
      return att_;
    }
    /**
     * <code>repeated .PropertyMsg att = 2;</code>
     *
     * <pre>
     *需要更新的属性
     * </pre>
     */
    public int getAttCount() {
      return att_.size();
    }
    /**
     * <code>repeated .PropertyMsg att = 2;</code>
     *
     * <pre>
     *需要更新的属性
     * </pre>
     */
    public com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg getAtt(int index) {
      return att_.get(index);
    }
    /**
     * <code>repeated .PropertyMsg att = 2;</code>
     *
     * <pre>
     *需要更新的属性
     * </pre>
     */
    public com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsgOrBuilder getAttOrBuilder(
        int index) {
      return att_.get(index);
    }

    private void initFields() {
      playerId_ = 0L;
      att_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlayerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playerId_);
      }
      for (int i = 0; i < att_.size(); i++) {
        output.writeMessage(2, att_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      for (int i = 0; i < att_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, att_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerAttUpdateMsg}
     *
     * <pre>
     *单个角色属性的更新
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerAttUpdateMsg)
        com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.empire.protocol.pb.player.PlayerAttUpdateProto.internal_static_PlayerAttUpdateMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.empire.protocol.pb.player.PlayerAttUpdateProto.internal_static_PlayerAttUpdateMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg.class, com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg.Builder.class);
      }

      // Construct using com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (attBuilder_ == null) {
          att_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          attBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.empire.protocol.pb.player.PlayerAttUpdateProto.internal_static_PlayerAttUpdateMsg_descriptor;
      }

      public com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg getDefaultInstanceForType() {
        return com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg.getDefaultInstance();
      }

      public com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg build() {
        com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg buildPartial() {
        com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg result = new com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerId_ = playerId_;
        if (attBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            att_ = java.util.Collections.unmodifiableList(att_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.att_ = att_;
        } else {
          result.att_ = attBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg) {
          return mergeFrom((com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg other) {
        if (other == com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg.getDefaultInstance()) return this;
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (attBuilder_ == null) {
          if (!other.att_.isEmpty()) {
            if (att_.isEmpty()) {
              att_ = other.att_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAttIsMutable();
              att_.addAll(other.att_);
            }
            onChanged();
          }
        } else {
          if (!other.att_.isEmpty()) {
            if (attBuilder_.isEmpty()) {
              attBuilder_.dispose();
              attBuilder_ = null;
              att_ = other.att_;
              bitField0_ = (bitField0_ & ~0x00000002);
              attBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttFieldBuilder() : null;
            } else {
              attBuilder_.addAllMessages(other.att_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayerId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.app.empire.protocol.pb.player.PlayerAttUpdateProto.PlayerAttUpdateMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long playerId_ ;
      /**
       * <code>required int64 playerId = 1;</code>
       *
       * <pre>
       *角色ID
       * </pre>
       */
      public boolean hasPlayerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 playerId = 1;</code>
       *
       * <pre>
       *角色ID
       * </pre>
       */
      public long getPlayerId() {
        return playerId_;
      }
      /**
       * <code>required int64 playerId = 1;</code>
       *
       * <pre>
       *角色ID
       * </pre>
       */
      public Builder setPlayerId(long value) {
        bitField0_ |= 0x00000001;
        playerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 playerId = 1;</code>
       *
       * <pre>
       *角色ID
       * </pre>
       */
      public Builder clearPlayerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg> att_ =
        java.util.Collections.emptyList();
      private void ensureAttIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          att_ = new java.util.ArrayList<com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg>(att_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.Builder, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsgOrBuilder> attBuilder_;

      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public java.util.List<com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg> getAttList() {
        if (attBuilder_ == null) {
          return java.util.Collections.unmodifiableList(att_);
        } else {
          return attBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public int getAttCount() {
        if (attBuilder_ == null) {
          return att_.size();
        } else {
          return attBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg getAtt(int index) {
        if (attBuilder_ == null) {
          return att_.get(index);
        } else {
          return attBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public Builder setAtt(
          int index, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg value) {
        if (attBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttIsMutable();
          att_.set(index, value);
          onChanged();
        } else {
          attBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public Builder setAtt(
          int index, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.Builder builderForValue) {
        if (attBuilder_ == null) {
          ensureAttIsMutable();
          att_.set(index, builderForValue.build());
          onChanged();
        } else {
          attBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public Builder addAtt(com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg value) {
        if (attBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttIsMutable();
          att_.add(value);
          onChanged();
        } else {
          attBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public Builder addAtt(
          int index, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg value) {
        if (attBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttIsMutable();
          att_.add(index, value);
          onChanged();
        } else {
          attBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public Builder addAtt(
          com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.Builder builderForValue) {
        if (attBuilder_ == null) {
          ensureAttIsMutable();
          att_.add(builderForValue.build());
          onChanged();
        } else {
          attBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public Builder addAtt(
          int index, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.Builder builderForValue) {
        if (attBuilder_ == null) {
          ensureAttIsMutable();
          att_.add(index, builderForValue.build());
          onChanged();
        } else {
          attBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public Builder addAllAtt(
          java.lang.Iterable<? extends com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg> values) {
        if (attBuilder_ == null) {
          ensureAttIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, att_);
          onChanged();
        } else {
          attBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public Builder clearAtt() {
        if (attBuilder_ == null) {
          att_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          attBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public Builder removeAtt(int index) {
        if (attBuilder_ == null) {
          ensureAttIsMutable();
          att_.remove(index);
          onChanged();
        } else {
          attBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.Builder getAttBuilder(
          int index) {
        return getAttFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsgOrBuilder getAttOrBuilder(
          int index) {
        if (attBuilder_ == null) {
          return att_.get(index);  } else {
          return attBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public java.util.List<? extends com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsgOrBuilder> 
           getAttOrBuilderList() {
        if (attBuilder_ != null) {
          return attBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(att_);
        }
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.Builder addAttBuilder() {
        return getAttFieldBuilder().addBuilder(
            com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.Builder addAttBuilder(
          int index) {
        return getAttFieldBuilder().addBuilder(
            index, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .PropertyMsg att = 2;</code>
       *
       * <pre>
       *需要更新的属性
       * </pre>
       */
      public java.util.List<com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.Builder> 
           getAttBuilderList() {
        return getAttFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.Builder, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsgOrBuilder> 
          getAttFieldBuilder() {
        if (attBuilder_ == null) {
          attBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsg.Builder, com.app.empire.protocol.pb.army.PropertyMsgProto.PropertyMsgOrBuilder>(
                  att_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          att_ = null;
        }
        return attBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PlayerAttUpdateMsg)
    }

    static {
      defaultInstance = new PlayerAttUpdateMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerAttUpdateMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerAttUpdateMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerAttUpdateMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037player/PlayerAttUpdateMsg.proto\032\026army/" +
      "PropertyMsg.proto\"A\n\022PlayerAttUpdateMsg\022" +
      "\020\n\010playerId\030\001 \002(\003\022\031\n\003att\030\002 \003(\0132\014.Propert" +
      "yMsgB9\n!com.app.empire.protocol.pb.playe" +
      "rB\024PlayerAttUpdateProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.app.empire.protocol.pb.army.PropertyMsgProto.getDescriptor(),
        }, assigner);
    internal_static_PlayerAttUpdateMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerAttUpdateMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerAttUpdateMsg_descriptor,
        new java.lang.String[] { "PlayerId", "Att", });
    com.app.empire.protocol.pb.army.PropertyMsgProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
