// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: campaign/CampaignTaskInfoMsg.proto

package com.app.empire.protocol.pb.campaign;

public final class CampaignTaskInfoMsgProto {
  private CampaignTaskInfoMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CampaignTaskInfoMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CampaignTaskInfoMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 campaignId = 1;</code>
     *
     * <pre>
     *副本唯一ID
     * </pre>
     */
    boolean hasCampaignId();
    /**
     * <code>optional int32 campaignId = 1;</code>
     *
     * <pre>
     *副本唯一ID
     * </pre>
     */
    int getCampaignId();

    /**
     * <code>optional int32 taskId = 2;</code>
     *
     * <pre>
     *任务模板ID
     * </pre>
     */
    boolean hasTaskId();
    /**
     * <code>optional int32 taskId = 2;</code>
     *
     * <pre>
     *任务模板ID
     * </pre>
     */
    int getTaskId();

    /**
     * <code>optional int32 status = 3;</code>
     *
     * <pre>
     *当前任务状态 1 进行中,2 进行中,但已达成任务条件，等通关, 3 成功, 4 失败, 5 已经结算;
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 3;</code>
     *
     * <pre>
     *当前任务状态 1 进行中,2 进行中,但已达成任务条件，等通关, 3 成功, 4 失败, 5 已经结算;
     * </pre>
     */
    int getStatus();

    /**
     * <code>optional int32 progress = 4;</code>
     *
     * <pre>
     *进度
     * </pre>
     */
    boolean hasProgress();
    /**
     * <code>optional int32 progress = 4;</code>
     *
     * <pre>
     *进度
     * </pre>
     */
    int getProgress();
  }
  /**
   * Protobuf type {@code CampaignTaskInfoMsg}
   */
  public static final class CampaignTaskInfoMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CampaignTaskInfoMsg)
      CampaignTaskInfoMsgOrBuilder {
    // Use CampaignTaskInfoMsg.newBuilder() to construct.
    private CampaignTaskInfoMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CampaignTaskInfoMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CampaignTaskInfoMsg defaultInstance;
    public static CampaignTaskInfoMsg getDefaultInstance() {
      return defaultInstance;
    }

    public CampaignTaskInfoMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CampaignTaskInfoMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              campaignId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              taskId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              status_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              progress_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.internal_static_CampaignTaskInfoMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.internal_static_CampaignTaskInfoMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg.class, com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<CampaignTaskInfoMsg> PARSER =
        new com.google.protobuf.AbstractParser<CampaignTaskInfoMsg>() {
      public CampaignTaskInfoMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CampaignTaskInfoMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CampaignTaskInfoMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CAMPAIGNID_FIELD_NUMBER = 1;
    private int campaignId_;
    /**
     * <code>optional int32 campaignId = 1;</code>
     *
     * <pre>
     *副本唯一ID
     * </pre>
     */
    public boolean hasCampaignId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 campaignId = 1;</code>
     *
     * <pre>
     *副本唯一ID
     * </pre>
     */
    public int getCampaignId() {
      return campaignId_;
    }

    public static final int TASKID_FIELD_NUMBER = 2;
    private int taskId_;
    /**
     * <code>optional int32 taskId = 2;</code>
     *
     * <pre>
     *任务模板ID
     * </pre>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 taskId = 2;</code>
     *
     * <pre>
     *任务模板ID
     * </pre>
     */
    public int getTaskId() {
      return taskId_;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>optional int32 status = 3;</code>
     *
     * <pre>
     *当前任务状态 1 进行中,2 进行中,但已达成任务条件，等通关, 3 成功, 4 失败, 5 已经结算;
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 status = 3;</code>
     *
     * <pre>
     *当前任务状态 1 进行中,2 进行中,但已达成任务条件，等通关, 3 成功, 4 失败, 5 已经结算;
     * </pre>
     */
    public int getStatus() {
      return status_;
    }

    public static final int PROGRESS_FIELD_NUMBER = 4;
    private int progress_;
    /**
     * <code>optional int32 progress = 4;</code>
     *
     * <pre>
     *进度
     * </pre>
     */
    public boolean hasProgress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 progress = 4;</code>
     *
     * <pre>
     *进度
     * </pre>
     */
    public int getProgress() {
      return progress_;
    }

    private void initFields() {
      campaignId_ = 0;
      taskId_ = 0;
      status_ = 0;
      progress_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, campaignId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, taskId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, progress_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, campaignId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, taskId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, progress_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CampaignTaskInfoMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CampaignTaskInfoMsg)
        com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.internal_static_CampaignTaskInfoMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.internal_static_CampaignTaskInfoMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg.class, com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg.Builder.class);
      }

      // Construct using com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        campaignId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        progress_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.internal_static_CampaignTaskInfoMsg_descriptor;
      }

      public com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg getDefaultInstanceForType() {
        return com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg.getDefaultInstance();
      }

      public com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg build() {
        com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg buildPartial() {
        com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg result = new com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.campaignId_ = campaignId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.taskId_ = taskId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.progress_ = progress_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg) {
          return mergeFrom((com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg other) {
        if (other == com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg.getDefaultInstance()) return this;
        if (other.hasCampaignId()) {
          setCampaignId(other.getCampaignId());
        }
        if (other.hasTaskId()) {
          setTaskId(other.getTaskId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasProgress()) {
          setProgress(other.getProgress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.app.empire.protocol.pb.campaign.CampaignTaskInfoMsgProto.CampaignTaskInfoMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int campaignId_ ;
      /**
       * <code>optional int32 campaignId = 1;</code>
       *
       * <pre>
       *副本唯一ID
       * </pre>
       */
      public boolean hasCampaignId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 campaignId = 1;</code>
       *
       * <pre>
       *副本唯一ID
       * </pre>
       */
      public int getCampaignId() {
        return campaignId_;
      }
      /**
       * <code>optional int32 campaignId = 1;</code>
       *
       * <pre>
       *副本唯一ID
       * </pre>
       */
      public Builder setCampaignId(int value) {
        bitField0_ |= 0x00000001;
        campaignId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 campaignId = 1;</code>
       *
       * <pre>
       *副本唯一ID
       * </pre>
       */
      public Builder clearCampaignId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        campaignId_ = 0;
        onChanged();
        return this;
      }

      private int taskId_ ;
      /**
       * <code>optional int32 taskId = 2;</code>
       *
       * <pre>
       *任务模板ID
       * </pre>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 taskId = 2;</code>
       *
       * <pre>
       *任务模板ID
       * </pre>
       */
      public int getTaskId() {
        return taskId_;
      }
      /**
       * <code>optional int32 taskId = 2;</code>
       *
       * <pre>
       *任务模板ID
       * </pre>
       */
      public Builder setTaskId(int value) {
        bitField0_ |= 0x00000002;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 taskId = 2;</code>
       *
       * <pre>
       *任务模板ID
       * </pre>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        taskId_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>optional int32 status = 3;</code>
       *
       * <pre>
       *当前任务状态 1 进行中,2 进行中,但已达成任务条件，等通关, 3 成功, 4 失败, 5 已经结算;
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 status = 3;</code>
       *
       * <pre>
       *当前任务状态 1 进行中,2 进行中,但已达成任务条件，等通关, 3 成功, 4 失败, 5 已经结算;
       * </pre>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 3;</code>
       *
       * <pre>
       *当前任务状态 1 进行中,2 进行中,但已达成任务条件，等通关, 3 成功, 4 失败, 5 已经结算;
       * </pre>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 3;</code>
       *
       * <pre>
       *当前任务状态 1 进行中,2 进行中,但已达成任务条件，等通关, 3 成功, 4 失败, 5 已经结算;
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }

      private int progress_ ;
      /**
       * <code>optional int32 progress = 4;</code>
       *
       * <pre>
       *进度
       * </pre>
       */
      public boolean hasProgress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 progress = 4;</code>
       *
       * <pre>
       *进度
       * </pre>
       */
      public int getProgress() {
        return progress_;
      }
      /**
       * <code>optional int32 progress = 4;</code>
       *
       * <pre>
       *进度
       * </pre>
       */
      public Builder setProgress(int value) {
        bitField0_ |= 0x00000008;
        progress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 progress = 4;</code>
       *
       * <pre>
       *进度
       * </pre>
       */
      public Builder clearProgress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        progress_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CampaignTaskInfoMsg)
    }

    static {
      defaultInstance = new CampaignTaskInfoMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CampaignTaskInfoMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CampaignTaskInfoMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CampaignTaskInfoMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"campaign/CampaignTaskInfoMsg.proto\"[\n\023" +
      "CampaignTaskInfoMsg\022\022\n\ncampaignId\030\001 \001(\005\022" +
      "\016\n\006taskId\030\002 \001(\005\022\016\n\006status\030\003 \001(\005\022\020\n\010progr" +
      "ess\030\004 \001(\005B?\n#com.app.empire.protocol.pb." +
      "campaignB\030CampaignTaskInfoMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CampaignTaskInfoMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CampaignTaskInfoMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CampaignTaskInfoMsg_descriptor,
        new java.lang.String[] { "CampaignId", "TaskId", "Status", "Progress", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
