// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error/ErrorMsg.proto

package com.app.empire.protocol.pb.error;

public final class ErrorMsgProto {
  private ErrorMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ErrorMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ErrorMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 errorType = 1;</code>
     *
     * <pre>
     * 错误对应协议
     * </pre>
     */
    boolean hasErrorType();
    /**
     * <code>optional int32 errorType = 1;</code>
     *
     * <pre>
     * 错误对应协议
     * </pre>
     */
    int getErrorType();

    /**
     * <code>optional int32 errorSubType = 2;</code>
     *
     * <pre>
     * 错误对应协议
     * </pre>
     */
    boolean hasErrorSubType();
    /**
     * <code>optional int32 errorSubType = 2;</code>
     *
     * <pre>
     * 错误对应协议
     * </pre>
     */
    int getErrorSubType();

    /**
     * <code>optional int32 code = 3;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>optional int32 code = 3;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    int getCode();

    /**
     * <code>optional string msg = 4;</code>
     *
     * <pre>
     * 消息
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 4;</code>
     *
     * <pre>
     * 消息
     * </pre>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 4;</code>
     *
     * <pre>
     * 消息
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code ErrorMsg}
   */
  public static final class ErrorMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ErrorMsg)
      ErrorMsgOrBuilder {
    // Use ErrorMsg.newBuilder() to construct.
    private ErrorMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ErrorMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ErrorMsg defaultInstance;
    public static ErrorMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ErrorMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ErrorMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errorType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              errorSubType_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              code_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              msg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.app.empire.protocol.pb.error.ErrorMsgProto.internal_static_ErrorMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.app.empire.protocol.pb.error.ErrorMsgProto.internal_static_ErrorMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg.class, com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ErrorMsg> PARSER =
        new com.google.protobuf.AbstractParser<ErrorMsg>() {
      public ErrorMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ErrorMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ERRORTYPE_FIELD_NUMBER = 1;
    private int errorType_;
    /**
     * <code>optional int32 errorType = 1;</code>
     *
     * <pre>
     * 错误对应协议
     * </pre>
     */
    public boolean hasErrorType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 errorType = 1;</code>
     *
     * <pre>
     * 错误对应协议
     * </pre>
     */
    public int getErrorType() {
      return errorType_;
    }

    public static final int ERRORSUBTYPE_FIELD_NUMBER = 2;
    private int errorSubType_;
    /**
     * <code>optional int32 errorSubType = 2;</code>
     *
     * <pre>
     * 错误对应协议
     * </pre>
     */
    public boolean hasErrorSubType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 errorSubType = 2;</code>
     *
     * <pre>
     * 错误对应协议
     * </pre>
     */
    public int getErrorSubType() {
      return errorSubType_;
    }

    public static final int CODE_FIELD_NUMBER = 3;
    private int code_;
    /**
     * <code>optional int32 code = 3;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 code = 3;</code>
     *
     * <pre>
     * 错误码
     * </pre>
     */
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 4;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 4;</code>
     *
     * <pre>
     * 消息
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string msg = 4;</code>
     *
     * <pre>
     * 消息
     * </pre>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 4;</code>
     *
     * <pre>
     * 消息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      errorType_ = 0;
      errorSubType_ = 0;
      code_ = 0;
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errorType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, errorSubType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, code_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorSubType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, code_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ErrorMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ErrorMsg)
        com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.app.empire.protocol.pb.error.ErrorMsgProto.internal_static_ErrorMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.app.empire.protocol.pb.error.ErrorMsgProto.internal_static_ErrorMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg.class, com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg.Builder.class);
      }

      // Construct using com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errorType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorSubType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.app.empire.protocol.pb.error.ErrorMsgProto.internal_static_ErrorMsg_descriptor;
      }

      public com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg getDefaultInstanceForType() {
        return com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg.getDefaultInstance();
      }

      public com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg build() {
        com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg buildPartial() {
        com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg result = new com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorType_ = errorType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorSubType_ = errorSubType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg) {
          return mergeFrom((com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg other) {
        if (other == com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg.getDefaultInstance()) return this;
        if (other.hasErrorType()) {
          setErrorType(other.getErrorType());
        }
        if (other.hasErrorSubType()) {
          setErrorSubType(other.getErrorSubType());
        }
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000008;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.app.empire.protocol.pb.error.ErrorMsgProto.ErrorMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int errorType_ ;
      /**
       * <code>optional int32 errorType = 1;</code>
       *
       * <pre>
       * 错误对应协议
       * </pre>
       */
      public boolean hasErrorType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 errorType = 1;</code>
       *
       * <pre>
       * 错误对应协议
       * </pre>
       */
      public int getErrorType() {
        return errorType_;
      }
      /**
       * <code>optional int32 errorType = 1;</code>
       *
       * <pre>
       * 错误对应协议
       * </pre>
       */
      public Builder setErrorType(int value) {
        bitField0_ |= 0x00000001;
        errorType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorType = 1;</code>
       *
       * <pre>
       * 错误对应协议
       * </pre>
       */
      public Builder clearErrorType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorType_ = 0;
        onChanged();
        return this;
      }

      private int errorSubType_ ;
      /**
       * <code>optional int32 errorSubType = 2;</code>
       *
       * <pre>
       * 错误对应协议
       * </pre>
       */
      public boolean hasErrorSubType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 errorSubType = 2;</code>
       *
       * <pre>
       * 错误对应协议
       * </pre>
       */
      public int getErrorSubType() {
        return errorSubType_;
      }
      /**
       * <code>optional int32 errorSubType = 2;</code>
       *
       * <pre>
       * 错误对应协议
       * </pre>
       */
      public Builder setErrorSubType(int value) {
        bitField0_ |= 0x00000002;
        errorSubType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorSubType = 2;</code>
       *
       * <pre>
       * 错误对应协议
       * </pre>
       */
      public Builder clearErrorSubType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorSubType_ = 0;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 3;</code>
       *
       * <pre>
       * 错误码
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 code = 3;</code>
       *
       * <pre>
       * 错误码
       * </pre>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 3;</code>
       *
       * <pre>
       * 错误码
       * </pre>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000004;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 3;</code>
       *
       * <pre>
       * 错误码
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 4;</code>
       *
       * <pre>
       * 消息
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string msg = 4;</code>
       *
       * <pre>
       * 消息
       * </pre>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 4;</code>
       *
       * <pre>
       * 消息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 4;</code>
       *
       * <pre>
       * 消息
       * </pre>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 4;</code>
       *
       * <pre>
       * 消息
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000008);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 4;</code>
       *
       * <pre>
       * 消息
       * </pre>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ErrorMsg)
    }

    static {
      defaultInstance = new ErrorMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ErrorMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ErrorMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024error/ErrorMsg.proto\"N\n\010ErrorMsg\022\021\n\ter" +
      "rorType\030\001 \001(\005\022\024\n\014errorSubType\030\002 \001(\005\022\014\n\004c" +
      "ode\030\003 \001(\005\022\013\n\003msg\030\004 \001(\tB1\n com.app.empire" +
      ".protocol.pb.errorB\rErrorMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ErrorMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ErrorMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ErrorMsg_descriptor,
        new java.lang.String[] { "ErrorType", "ErrorSubType", "Code", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
